name: LevelRestrictionPlugin
version: '${project.version}'
main: com.maks.levelrestrictionplugin.LevelRestrictionPlugin
api-version: '1.20'
commands:
  items_lvl:
    description: Reloads the items.yml configuration
    usage: /<command> reload
    permission: items_lvl.reload